cmake_minimum_required(VERSION 3.22.0)

project(SharedUtils CXX C)

file(GLOB_RECURSE SRC_FILES     LIST_DIRECTORIES false RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} *.c??)
file(GLOB_RECURSE HEADER_FILES  LIST_DIRECTORIES false RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} *.h)

message(STATUS "Source Files: " ${SRC_FILES})

if(NOT SRC_FILES STREQUAL "")
    message(STATUS "Adding Shared Library")
    add_library(SharedUtils ${SRC_FILES} ${HEADER_FILES})

    set_property(TARGET SharedUtils PROPERTY CXX_STANDARD 23)
    set_property(TARGET SharedUtils PROPERTY CXX_STANDARD_REQUIRED ON)

    # target_link_libraries(SharedUtils PUBLIC opengl32 glad)
endif()